#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in2,    rightLiftPot,   sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    pPowerExp,      sensorAnalog)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  leftButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  rightButton,    sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rMobGoal,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           lLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lFront,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rFront,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chainBar,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rBack,         tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port8,           lBack,         tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port9,           rLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lMobGoal,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
