#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    pPowerExp,      sensorAnalog)
#pragma config(Sensor, dgtl1,  Red,            sensorDigitalIn)
#pragma config(Sensor, dgtl2,  Straight,       sensorDigitalIn)
#pragma config(Sensor, dgtl3,  None,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftGoal,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftFront,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           RightFront,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftMid,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RightMid,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftRear,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           RightRear,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RightGoal,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
